# GPU Stats

In [1]:
import msprime
import numpy as np
from pg_gpu.haplotype_matrix import HaplotypeMatrix


In [2]:
# do a simulation
ts = msprime.sim_ancestry(
    samples=10,
    sequence_length=1e5,
    recombination_rate=1e-8,
    population_size=10000,
    ploidy=2,
    discrete_genome=False
    )
ts = msprime.sim_mutations(ts, rate=1e-8, model="binary")

In [3]:
# create a haplotype matrix
h = HaplotypeMatrix.from_ts(ts)

# compute pi, compare to tskit
print(ts.diversity(mode="site"))
print(h.diversity(span_normalize=True))

# compute pairwise LD
D = h.pairwise_LD_v()

0.0004313684210526322
0.0004313684210526315


In [6]:
print(D)

[[ 0.     -0.01    0.16   ... -0.01    0.      0.    ]
 [-0.01    0.     -0.01   ... -0.0025 -0.0125 -0.0125]
 [ 0.16   -0.01    0.     ... -0.01    0.      0.    ]
 ...
 [-0.01   -0.0025 -0.01   ...  0.     -0.0125 -0.0125]
 [ 0.     -0.0125  0.     ... -0.0125  0.      0.1875]
 [ 0.     -0.0125  0.     ... -0.0125  0.1875  0.    ]]
